# Generated by Django 4.2.7 on 2024-02-26 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendartimely', '0003_remove_event_repeat_event_repeat_frequency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_repeat',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='repeat_frequency',
            field=models.CharField(blank=True, choices=[('D', 'Daily'), ('W', 'Weekly'), ('M', 'Monthly'), ('Y', 'Yearly')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='repeat_interval',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
